name: s3

on: 
  workflow_dispatch:

env: 
   AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY}}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY}}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9

      - name: Initialize Terraform
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.SSH_KEY_GITHUB_ACTIONS}}'
          terraform init
        

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Format Terraform Files
        run: terraform fmt -check

      - name: Plan Terraform Deployment
        run: terraform plan

      - name: Apply Terraform Deployment
        run: terraform apply -auto-approve